In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [26]:
import numpy as np
import matplotlib.pyplot as plt


In [27]:
from sklearn.datasets import load_digits
digits = load_digits()


In [28]:
X = digits.data
Y = digits.target
print(X.shape, Y.shape)


(1797, 64) (1797,)


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)


In [30]:
LR = LogisticRegression()
LR = LR.fit(X_train, Y_train)
LR.score(X_test, Y_test)


/home/jubaer/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [31]:
SV = SVC()
SV = SV.fit(X_train, Y_train)
SV.score(X_test, Y_test)


0.9851851851851852

In [32]:
RF = RandomForestClassifier(n_estimators=40)
RF = RF.fit(X_train, Y_train)
RF.score(X_test, Y_test)


0.9592592592592593

In [33]:
from sklearn.model_selection import KFold
KF = KFold(n_splits=3)
KF


KFold(n_splits=3, random_state=None, shuffle=False)

In [34]:
for train_index, test_index in KF.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [36]:
def get_score(model, X_train, Y_train, X_test, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)


In [37]:
get_score(SVC(), X_train, Y_train, X_test, Y_test)

0.9851851851851852

In [50]:
# to select uniformly according to target attribute
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)

lr_score = []
svm_score = []
rf_score = []
for train_index, test_index in folds.split(X, Y):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    lr_score.append(get_score(LogisticRegression(), X_train, Y_train, X_test, Y_test))
    svm_score.append(get_score(SVC(), X_train, Y_train, X_test, Y_test))
    rf_score.append(get_score(RandomForestClassifier(n_estimators=50), X_train, Y_train, X_test, Y_test))


/home/jubaer/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/jubaer/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regressi

In [53]:
print('LR:', np.mean(lr_score))
print('SVM:',np.mean(svm_score))
print('RF',np.mean(svm_score))

LR: 0.928193668528864
SVM: 0.9699503414028554
RF 0.9699503414028554


In [65]:
# Using builtin functions
# Same as the above for loop
from sklearn.model_selection import cross_val_score
lr_score = cross_val_score(LogisticRegression(), X, Y, cv=10)
svm_score = cross_val_score(SVC(), X, Y, cv=10)
rf_score = cross_val_score(RandomForestClassifier(n_estimators=10), X, Y, cv=10)


/home/jubaer/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/jubaer/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regressi

In [66]:
print('LR:', np.mean(lr_score))
print('SVM:',np.mean(svm_score))
print('RF',np.mean(svm_score))

LR: 0.928193668528864
SVM: 0.9699503414028554
RF 0.9699503414028554
