<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("../datasets/0_homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

/home/jubaer/.local/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>




In [8]:
import pickle

In [10]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [11]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [12]:
mp.coef_

array([135.78767123])

In [13]:
mp.intercept_

180616.43835616432

In [14]:
mp.predict([[5000]])

/home/jubaer/.local/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [17]:
import joblib

In [18]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [19]:
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

array([135.78767123])

In [20]:
mj.intercept_

180616.43835616432

In [21]:
mj.predict([[5000]])

/home/jubaer/.local/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])